.TH XFCE4-POWER-MANAGER 1 "Version 0.8.0" "31 March 2009"

.SH NAME
xfce4-power-manager-settings \- Settings dialog for the Xfce 4 Power manager

.SH SYNOPSIS
.B xfce4-power-manager-settings
.I [options]
.br

.SH DESCRIPTION
\fBxfce4-power-manager-settings\fP is a utility that comes with the Xfce4 
power manager to access/change its configuration.  It is a separate program 
that uses xfconf to load/save settings according to the user's choices. 
\fBxfce4-power-manager-settings\fP requires the Xfce4 power manager to be 
running because it connects to it via DBus and gets information about which 
settings should and should not be displayed; for  example,  the 
\fBxfce4-power-manager-settings\fP utility will not show the LCD brightness 
settings if no device was detected by the running instance of the Xfce4 power 
manager. 
.br
.br
 \fBxfce4-power-manager-settings\fP does not have any command line options.

.SH BUGS
Please report bugs to
.IR http://bugzilla.xfce.org/ .
Development discussion should be conducted on the
.IR goodies-dev@xfce.org
mailing list.  Usage-related questions should be directed to the
.IR xfce@xfce.org
mailing list.

.SH HOMEPAGE
.I http://goodies.xfce.org/

.SH AUTHOR
Ali Abdallah <aliov@xfce.org>

.SH MANPAGE AUTHORS
Ali Abdallah <aliov@xfce.org>,
Robby Workman <rworkman@slackware.com>.
